{{- $root := . }}
{{- range $path, $bytes := .Files.Glob "config/templates/**.json" }}
{{- $filename := base $path }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "push-{{ trimSuffix (ext $filename) $filename }}-template"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    app: "{{ template "gocd.name" $root }}"
    heritage: "{{ $root.Release.Service }}"
    release: "{{ $root.Release.Name }}"
spec:
  template:
    metadata:
      name: "push-{{ trimSuffix (ext $filename) $filename }}-template"
      labels:
        chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
        app: "{{ template "gocd.name" $root }}"
        heritage: "{{ $root.Release.Service }}"
        release: "{{ $root.Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: "push-{{ trimSuffix (ext $filename) $filename }}-template"
        image: appropriate/curl:latest
        args:
        - http://{{ template "gocd.fullname" $root }}-server.{{ $root.Release.Namespace }}.svc.cluster.local:8153/go/api/admin/templates
        - --fail
        - -X
        - POST
        - -H
        - 'Accept: application/vnd.go.cd.v4+json'
        - -H
        - 'Content-Type: application/json'
        - -d
        - |-
{{ $root.Files.Get $path | indent 10 }}
{{- end }}